variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: '*/*/'
  RESHARPER_SOLUTION_NAME: 'DungeonEscape.sln'
  RESHARPER_EXCLUDE: 'Nez.Portable/**;DungeonEscape/Content/*.tsx'
  RESHARPER_THRESHOLD: 0
  PUBLISH_PROJECT: 'DungeonEscape/DungeonEscape.csproj'

stages:
  - build
  - scan
  - test
  - publish

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json'
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*'
    - '$NUGET_PACKAGES_DIRECTORY'

  policy: pull-push

before_script:
  - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY'

build:
  image: mcr.microsoft.com/dotnet/sdk:7.0
  stage: build
  script:
    - 'dotnet build --no-restore'

tests:
  image: mcr.microsoft.com/dotnet/sdk:7.0
  stage: test
  script:
    - 'dotnet test --no-restore'

resharper-scan:
  image: registry.gitlab.com/cjburchell/reshaper:2021.2.2-net7-819703864
  stage: scan
  script:
    - '/tools/jb inspectcode --exclude=$RESHARPER_EXCLUDE -o=RsInspection.xml --caches-home=temp $RESHARPER_SOLUTION_NAME --toolset=16.0'
    - 'dotnet /tools/checkwarnings/checkwarnings.dll --file=RsInspection.xml --threshold=$RESHARPER_THRESHOLD'
  dependencies:
    - build
  artifacts:
    when: always
    paths:
      - RsInspection.xml

publish-windows:
  image: mcr.microsoft.com/dotnet/sdk:7.0
  stage: publish
  only:
    - tags
  except:
    - branches
  artifacts:
    when: always
    paths:
      - de
  script:
    - 'dotnet publish -c Release -o de -r win10-x64 $PUBLISH_PROJECT'

